
public interface Constants {

	// World Variables
	int WORLD_WIDTH = 50;
	int WORLD_HEIGHT = 25;
	int MAX_SIMULATION_LENGTH = 10000;
	int INIT_FROBS = 40;
	int INIT_GRASSES = 40;
	int INIT_ROCKS = 50;
	
	// Hit Penalties
	int ROCK_BUMP_PENALTY = 30;
	int FROB_HIT_PENALTY = 10;
	
	// Grass Constants
	int GRASS_FIXED_OVERHEAD = 0;
	int GRASS_GENESIS_MASS = 10;
	int GRASS_BIRTH_MASS = 30;
	int GRASS_UPDATE_PERIOD = 10;
	int GRASS_CROWD_LIMIT = 	2;
	int GRASS_MAX_UPDATE_PERIOD = 100;
	int GRASS_BIRTH_PERCENT = 40;
	
	// Frob Constants
	int FROB_FIXED_OVERHEAD = 3;
	int FROB_GENESIS_MASS = 100;
	int DNA_MUTATION_ODDS_PER_BYTE = 20;
	
	// Mass Taxes
	int GRASS_MASS_TAX_MILLS = -20;
	int FROB_MASS_TAX_MILLS = 10;
	
	// Frob DNA byte names
	int DNA_BIRTH_MASS = 0;
	int DNA_BIRTH_PERCENT = 1;
	int DNA_UPDATE_PERIOD = 2;
	int NORTH_EMPTY_OFFSET = 3;
	int NORTH_ROCK_OFFSET = 4;
	int NORTH_GRASS_OFFSET = 5;
	int NORTH_FROB_OFFSET = 6;
	int SOUTH_EMPTY_OFFSET = 7;
	int SOUTH_ROCK_OFFSET = 8;
	int SOUTH_GRASS_OFFSET = 9;
	int SOUTH_FROB_OFFSET = 10;
	int EAST_EMPTY_OFFSET = 11;
	int EAST_ROCK_OFFSET = 12;
	int EAST_GRASS_OFFSET = 13;
	int EAST_FROB_OFFSET = 14;
	int WEST_EMPTY_OFFSET = 15;
	int WEST_ROCK_OFFSET = 16;
	int WEST_GRASS_OFFSET = 17;
	int WEST_FROB_OFFSET = 18;
	int DNA_LENGTH = 19;
}
